package com.teeny.wms.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.teeny.wms.model.ServerConfigEntity;

import com.teeny.wms.dao.ServerConfigEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig serverConfigEntityDaoConfig;

    private final ServerConfigEntityDao serverConfigEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        serverConfigEntityDaoConfig = daoConfigMap.get(ServerConfigEntityDao.class).clone();
        serverConfigEntityDaoConfig.initIdentityScope(type);

        serverConfigEntityDao = new ServerConfigEntityDao(serverConfigEntityDaoConfig, this);

        registerDao(ServerConfigEntity.class, serverConfigEntityDao);
    }
    
    public void clear() {
        serverConfigEntityDaoConfig.clearIdentityScope();
    }

    public ServerConfigEntityDao getServerConfigEntityDao() {
        return serverConfigEntityDao;
    }

}
