package com.teeny.wms.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.teeny.wms.model.ServerConfigEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "server_config".
*/
public class ServerConfigEntityDao extends AbstractDao<ServerConfigEntity, Long> {

    public static final String TABLENAME = "server_config";

    /**
     * Properties of entity ServerConfigEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ServerName = new Property(1, String.class, "serverName", false, "server_name");
        public final static Property ServerAddress = new Property(2, String.class, "serverAddress", false, "server_address");
        public final static Property Port = new Property(3, String.class, "port", false, "PORT");
    }


    public ServerConfigEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ServerConfigEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"server_config\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"server_name\" TEXT," + // 1: serverName
                "\"server_address\" TEXT," + // 2: serverAddress
                "\"PORT\" TEXT);"); // 3: port
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"server_config\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ServerConfigEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String serverName = entity.getServerName();
        if (serverName != null) {
            stmt.bindString(2, serverName);
        }
 
        String serverAddress = entity.getServerAddress();
        if (serverAddress != null) {
            stmt.bindString(3, serverAddress);
        }
 
        String port = entity.getPort();
        if (port != null) {
            stmt.bindString(4, port);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ServerConfigEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String serverName = entity.getServerName();
        if (serverName != null) {
            stmt.bindString(2, serverName);
        }
 
        String serverAddress = entity.getServerAddress();
        if (serverAddress != null) {
            stmt.bindString(3, serverAddress);
        }
 
        String port = entity.getPort();
        if (port != null) {
            stmt.bindString(4, port);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ServerConfigEntity readEntity(Cursor cursor, int offset) {
        ServerConfigEntity entity = new ServerConfigEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // serverName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // serverAddress
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // port
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ServerConfigEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setServerName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setServerAddress(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPort(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ServerConfigEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ServerConfigEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ServerConfigEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
