server:
  port: 8080
  address: 192.168.1.3
#  address: 192.168.31.60
  context-path: /wms

logging:
  level:
    org:
       springframework:
           security: DEBUG
    root: INFO
  file: log.log

spring:
  datasource:
    name: wms
    druid:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost;databaseName=yyt
#      username: sa
#      password: zhupeng123
      url: jdbc:sqlserver://yyt8812.gnway.cc:1344;databaseName=nmgce
      username: sa
      password: yyt@123
      initial-size: 1
      min-idle: 1
      max-active: 20
      filters: stat,slf4j
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.teeny.wms.web.model
  executor-type: batch
security:
  oauth2:
    client:
      authentication-scheme: header
      access-token-validity-seconds: 43200
      refresh-token-validity-seconds: 43200









