server:
  port: 8080
  address: 192.168.1.3
  context-path: /wms

logging:
  level:
    org:
       springframework:
           security: DEBUG
    root: INFO
  file: log.log

spring:
  datasource:
    druid:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://yyt8812.gnway.cc:1344;databaseName=nmgce
      username: sa
      password: yyt@123
      initial-size: 1
      min-idle: 1
      max-active: 20
      filters: stat,slf4j
      name: wms
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.teeny.wms.web.model
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-prefix: WMS
    jdbc-type-for-null: varchar
security:
  oauth2:
    client:
      authentication-scheme: header
      access-token-validity-seconds: 43200
      refresh-token-validity-seconds: 43200
      access-token-uri: /oauth/token
      authorities: PLATFORM
      authorized-grant-types: password, refresh_token
      client-authentication-scheme: header
      client-id: wms
      client-secret: secret
      scope: secret
      resource-ids: resource_id
  basic:
    authorize-mode: role
    enabled: true
    path: /api/**
  headers:
    cache: true
    content-type: false
  sessions: stateless
debug: false






